/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.UserController;
import java.io.IOException;
import model.Noti;
import model.User;

/**
 *
 * @author linhc
 */
public class HomeAdmin extends javax.swing.JFrame {
    // Tạo 1 userController để có thể sử lý logic liên quan đến dữ liệu của User
    private UserController control = new UserController();
    // Tạo 1 đối tượng Notification để có thể dùng hiển thị các thông báo khi thực hiện 1 điều gì đó. Tối ưu sử dụng lại code
    private Noti noti = new Noti(this);
    // 2 Biến giúp lưu thông tin sau khi đăng nhập. Để có thể lấy ra được thông tin trong file đưa lên màn hình.
    private String maSV;
    private String password;
    // đối tượng user để lưu dữ liệu user đó nhằm hiển thị lên màn hình
    User model = new User();
    
    /**
     * Creates new form HomeAdmin
     */
    public HomeAdmin(String maSV, String password) {
        initComponents();
        this.maSV = maSV;
        this.password = password;
        showInfor();
        pack();
    }
    
    // Phương thức hiển thị thông tin sinh viên lên màn hình khi View AdminStudent được khởi tạo (Hiển thị tên)
    private void showInfor(){
        // Lấy user thông qua controller
        try {
            model = control.getUse(maSV, password);
        } catch (IOException e) {
            noti.showNotiError("Loi " + e.toString());
        }
        // Hiển thị thông tin tên admin lên màn hình
        lableHello.setText(lableHello.getText() + " " + model.getFullName());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lableHello = new javax.swing.JLabel();
        btnQuanLySuKien = new javax.swing.JButton();
        btnQuanLySV = new javax.swing.JButton();
        btnLenLich = new javax.swing.JButton();
        btnThongKe = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Home");

        lableHello.setBackground(new java.awt.Color(0, 255, 255));
        lableHello.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lableHello.setForeground(new java.awt.Color(255, 0, 0));
        lableHello.setText("Xin chào admin, ");
        lableHello.setToolTipText("");
        lableHello.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 153), 4));

        btnQuanLySuKien.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnQuanLySuKien.setText("Quản lý sự kiện");
        btnQuanLySuKien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuanLySuKienActionPerformed(evt);
            }
        });

        btnQuanLySV.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnQuanLySV.setText("Quản lý thành viên");
        btnQuanLySV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuanLySVActionPerformed(evt);
            }
        });

        btnLenLich.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnLenLich.setText("Lên lịch phỏng vấn");
        btnLenLich.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLenLichActionPerformed(evt);
            }
        });

        btnThongKe.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnThongKe.setText("Thống kê");
        btnThongKe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThongKeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(btnQuanLySV, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnQuanLySuKien, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56))
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lableHello, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addComponent(btnLenLich, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 155, Short.MAX_VALUE)
                .addComponent(btnThongKe, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(94, 94, 94))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lableHello, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 94, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnQuanLySV, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnQuanLySuKien, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLenLich, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnThongKe, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(90, 90, 90))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnQuanLySVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuanLySVActionPerformed
        // TODO add your handling code here:
        new QLSinhVien(maSV, password).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnQuanLySVActionPerformed

    private void btnQuanLySuKienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuanLySuKienActionPerformed
        // TODO add your handling code here:
        new QLEvent(maSV, password).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnQuanLySuKienActionPerformed

    private void btnThongKeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThongKeActionPerformed
        // TODO add your handling code here:
        new Statistical(maSV, password).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnThongKeActionPerformed

    private void btnLenLichActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLenLichActionPerformed
        // TODO add your handling code here:
        new SetDateInterview(maSV, password).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnLenLichActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new HomeAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLenLich;
    private javax.swing.JButton btnQuanLySV;
    private javax.swing.JButton btnQuanLySuKien;
    private javax.swing.JButton btnThongKe;
    private javax.swing.JLabel lableHello;
    // End of variables declaration//GEN-END:variables
}
