/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.EventController;
import java.io.IOException;
import java.util.ArrayList;
import javax.swing.border.TitledBorder;
import javax.swing.table.DefaultTableModel;
import model.Event;
import model.Noti;

/**
 *
 * @author Lê Ngọc Trường
 */
public class QLEvent extends javax.swing.JFrame {

    // Tạo 1 đối tượng EventController để có thể thao tác với dữ liệu Event
    EventController eventController = new EventController();
    // Tạo 1 đối tượng Notification để có thể dùng hiển thị các thông báo khi thực hiện 1 điều gì đó. Tối ưu sử dụng lại code
    Noti noti = new Noti(this);
    // Lưu thông tin danh sách Event
    ArrayList<Event> listEvent;
    // 2 biến lưu thông tin admin
    private String maSV;
    private String password;

    /**
     * Creates new form QLEvent
     */
    public QLEvent() {
        initComponents();
        pack();
    }

    public QLEvent(String masv, String password) {
        initComponents();
        pack();
        this.maSV = masv;
        this.password = password;
    }

        DefaultTableModel dmodel = new DefaultTableModel() {
        @Override
        public boolean isCellEditable(int row, int column) {
            // chỉ được xem, không được sửa row and column nào hết
            return false;
        }
    };
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelDanhSachEvent = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        // Tao DefaultTableModel va them row tieu de, va row thong tin Event
        DefaultTableModel model = new DefaultTableModel(){
            @Override
            public boolean isCellEditable(int row, int column) {
                // chỉ được xem, không được sửa row and column nào hết
                return false;
            }
        };
        model.addColumn("ID");
        model.addColumn("Tên sự kiện");
        model.addColumn("Ngày bắt đầu");
        model.addColumn("Ngày kết thúc");
        model.addColumn("Số lượng thành viên cần");
        model.addColumn("Số lượng thành viên thiếu");
        model.addColumn("Địa chỉ");
        model.addColumn("Tổng chi phí");
        try{
            listEvent = eventController.getListEvents();
        }catch(IOException e){
            noti.showNotiError("Có lỗi: " + e.toString());
        }
        catch(Exception e2){
            noti.showNotiError("Có lỗi: " + e2.toString());
        }

        // get các chi phí hoạt động có cùng IdEvent và đưa vào ListOperatingFee của Evend có IdEvent đó
        for(Event e : listEvent){
            try{
                eventController.setListOperatingFee(e);
            }
            catch(IOException e1){
                noti.showNotiError("Có lỗi: " + e1.toString());
            }
        }

        for(Event e : listEvent){
            long costTotal = eventController.getCostTotal(e);

            Object[] row = {e.getId(), e.getNameEvent(), e.getStartDay(), e.getEndDay(), e.getNumberOfStudent(),e.getNumberOfStudent() - e.getUsers().size(),e.getAddress(), costTotal};
            model.addRow(row);
        }
        tableEvent = new javax.swing.JTable(model);
        panelButton = new javax.swing.JPanel();
        btnExist = new javax.swing.JButton();
        btnAdd1 = new javax.swing.JButton();
        btnRepair = new javax.swing.JButton();
        btnAddUserToEvent = new javax.swing.JButton();
        btnFeeManager = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Quản lý sự kiện");

        panelDanhSachEvent.setBorder(javax.swing.BorderFactory.createTitledBorder("Danh sách sự kiện"));

        jScrollPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jScrollPane1MousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(tableEvent);

        javax.swing.GroupLayout panelDanhSachEventLayout = new javax.swing.GroupLayout(panelDanhSachEvent);
        panelDanhSachEvent.setLayout(panelDanhSachEventLayout);
        panelDanhSachEventLayout.setHorizontalGroup(
            panelDanhSachEventLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDanhSachEventLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1067, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelDanhSachEventLayout.setVerticalGroup(
            panelDanhSachEventLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDanhSachEventLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 312, Short.MAX_VALUE)
                .addContainerGap())
        );

        panelButton.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder("Chức năng")));

        btnExist.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        btnExist.setText("Thoát");
        btnExist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExistActionPerformed(evt);
            }
        });

        btnAdd1.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        btnAdd1.setText("Thêm sự kiện");
        btnAdd1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdd1ActionPerformed(evt);
            }
        });

        btnRepair.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        btnRepair.setText("Sửa thông tin sự kiện");
        btnRepair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRepairActionPerformed(evt);
            }
        });

        btnAddUserToEvent.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        btnAddUserToEvent.setText("Thêm thành viên tham gia sự kiện");
        btnAddUserToEvent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddUserToEventActionPerformed(evt);
            }
        });

        btnFeeManager.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        btnFeeManager.setText("Quản lý chi phí");
        btnFeeManager.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFeeManagerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelButtonLayout = new javax.swing.GroupLayout(panelButton);
        panelButton.setLayout(panelButtonLayout);
        panelButtonLayout.setHorizontalGroup(
            panelButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelButtonLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(btnAdd1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(btnRepair, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAddUserToEvent, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(btnFeeManager, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(btnExist, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelButtonLayout.setVerticalGroup(
            panelButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelButtonLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdd1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnExist, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnRepair, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAddUserToEvent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnFeeManager, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelDanhSachEvent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(128, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelDanhSachEvent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        panelDanhSachEvent.setBorder(new TitledBorder("Danh sách sự kiện"));
        panelButton.setBorder(new TitledBorder("Chức năng"));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExistActionPerformed
        new HomeAdmin(maSV, password).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnExistActionPerformed

    private void btnAdd1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdd1ActionPerformed
        new AddEvent().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnAdd1ActionPerformed

    private void btnFeeManagerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFeeManagerActionPerformed
        new QLOperationFee(maSV, password).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnFeeManagerActionPerformed

    private void btnRepairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRepairActionPerformed

<<<<<<< HEAD
        int index = tableEvent.getSelectedRow();
        // Lấy ra model của bảng đang dùng
        DefaultTableModel dmodel = (DefaultTableModel) tableEvent.getModel();
        if(index != -1){
            long idEvent = (long) dmodel.getValueAt(index, 0);
            System.out.println(idEvent);
            new RepairEvent(idEvent).setVisible(true);
            this.setVisible(false);
=======
    private void btnAddUserToEventActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddUserToEventActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnAddUserToEventActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QLEvent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QLEvent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QLEvent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QLEvent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
>>>>>>> b6059a865069eac202fca32083510a75c92e0080
        }
        else{
            noti.showNotiInformation("Vui lòng chọn sự kiện cần sửa");
        }
    }//GEN-LAST:event_btnRepairActionPerformed

    private void clicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clicked
        // TODO add your handling code here:


    }//GEN-LAST:event_clicked

    private void jScrollPane1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPane1MousePressed
        // TODO add your handling code here:

    }//GEN-LAST:event_jScrollPane1MousePressed

    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> {
            new QLEvent().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd1;
    private javax.swing.JButton btnAddUserToEvent;
    private javax.swing.JButton btnExist;
    private javax.swing.JButton btnFeeManager;
    private javax.swing.JButton btnRepair;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panelButton;
    private javax.swing.JPanel panelDanhSachEvent;
    private javax.swing.JTable tableEvent;
    // End of variables declaration//GEN-END:variables
}
