/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.EventController;
import controller.OperatingFeeController;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import model.Noti;
import model.OperatingFee;

/**
 *
 * @author Lê Ngọc Trường
 */
public class QLOperationFee extends javax.swing.JFrame {

    // Tạo 1 đối tượng OperatingFeeController để có thể thao tác với dữ liệu OperatingFee
    OperatingFeeController operatingFeeController = new OperatingFeeController();
    // Tạo 1 đối tượng EventController để có thể thao tác với dữ liệu Event
    EventController eventController = new EventController();
    // Tạo 1 đối tượng Notification để có thể dùng hiển thị các thông báo khi thực hiện 1 điều gì đó. Tối ưu sử dụng lại code
    Noti noti = new Noti(this);
    // Lưu thông tin danh sách Operation Fee
    ArrayList<OperatingFee> listOperatingFee;
    // 2 biến lưu thông tin admin
    private String maSV;
    private String password;

    // Tao 1 DefaultTableModel để đổ dữ liệu vào JTable, không thể sửa dữ liệu trực tiếp ở bảng
    DefaultTableModel dmodel = new DefaultTableModel() {
        @Override
        public boolean isCellEditable(int row, int column) {
            // chỉ được xem, không được sửa row and column nào hết
            return false;
        }
    };

    /**
     * Creates new form QLOperationFee
     */
    public QLOperationFee() {
        initComponents();
    }

    public QLOperationFee(String maSV, String password) {
        this.maSV = maSV;
        this.password = password;
        initComponents();
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelDanhSach = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        // Add các cột vào dmodel
        dmodel.addColumn("ID");
        dmodel.addColumn("Tên khoản phí");
        dmodel.addColumn("Kinh phí");
        dmodel.addColumn("Sự kiện");
        // Lấy ra list Operating Fee từ Controller
        try{
            listOperatingFee = operatingFeeController.getListCost();
        }catch(Exception e){
            noti.showNotiError("Có lỗi: " + e.toString());
        }
        // Đẩy từng khoản phí vào dmodel
        for(OperatingFee fee : listOperatingFee){
            // Lấy ra tên sự kiện thông qua IdEvent của OperatingFee
            String ev = "";
            try{
                ev = eventController.getEvent(fee.getIdEvent()).getNameEvent();
            }
            catch(Exception e1){
                noti.showNotiError("Có lỗi: " + e1.toString());
            }
            Object[] row = {fee.getId(), fee.getNameFee(), fee.getMoney(), ev};
            dmodel.addRow(row);
        }
        tableOperatingFee = new javax.swing.JTable(dmodel);
        jPanel1 = new javax.swing.JPanel();
        btnAdd = new javax.swing.JButton();
        btnExist = new javax.swing.JButton();
        btnRepair = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Quản lý chi phí");

        panelDanhSach.setBorder(javax.swing.BorderFactory.createTitledBorder("Danh sách chi phí"));

        tableOperatingFee.setModel(dmodel);
        jScrollPane1.setViewportView(tableOperatingFee);

        javax.swing.GroupLayout panelDanhSachLayout = new javax.swing.GroupLayout(panelDanhSach);
        panelDanhSach.setLayout(panelDanhSachLayout);
        panelDanhSachLayout.setHorizontalGroup(
            panelDanhSachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDanhSachLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 804, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelDanhSachLayout.setVerticalGroup(
            panelDanhSachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDanhSachLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 257, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Chức năng"));

        btnAdd.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        btnAdd.setText("Thêm chi phí");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnExist.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        btnExist.setText("Thoát");
        btnExist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExistActionPerformed(evt);
            }
        });

        btnRepair.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        btnRepair.setText("Sửa chi phí");
        btnRepair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRepairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 122, Short.MAX_VALUE)
                .addComponent(btnRepair, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(94, 94, 94)
                .addComponent(btnExist, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdd)
                    .addComponent(btnExist)
                    .addComponent(btnRepair))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(panelDanhSach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelDanhSach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        new AddOperatingFee(maSV, password).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnExistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExistActionPerformed
        // TODO add your handling code here:
        new QLEvent(maSV, password).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnExistActionPerformed

    private void btnRepairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRepairActionPerformed
        // TODO add your handling code here
        // Lấy index khi người dùng muốn sửa khoản phí nào trong bảng
        int index = tableOperatingFee.getSelectedRow();
        // Lấy ra model của bảng đang dùng
        DefaultTableModel dmodel = (DefaultTableModel) tableOperatingFee.getModel();
        if(index != -1){
            // Lấy ra id của khoản phí đấy
            long iDOF = (long) dmodel.getValueAt(index, 0);
            new RepairOperatingFee(maSV, password,iDOF).setVisible(true);
            this.setVisible(false);
        }
        else{
            noti.showNotiInformation("Vui lòng chọn khoản phí cần sửa");
        }
    }//GEN-LAST:event_btnRepairActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QLOperationFee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QLOperationFee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QLOperationFee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QLOperationFee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QLOperationFee().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnExist;
    private javax.swing.JButton btnRepair;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panelDanhSach;
    private javax.swing.JTable tableOperatingFee;
    // End of variables declaration//GEN-END:variables
}
