/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.UserController;
import java.io.IOException;
import java.util.ArrayList;
import javax.swing.border.TitledBorder;
import javax.swing.table.DefaultTableModel;
import model.Noti;
import model.User;

/**
 *
 * @author Lê Ngọc Trường
 */
public class QLSinhVien extends javax.swing.JFrame {
    // Tạo 1 User Controller để thao tác với dữ liệu User
    UserController userController = new UserController();
    // Tạo 1 đối tượng Notification để có thể dùng hiển thị các thông báo khi thực hiện 1 điều gì đó. Tối ưu sử dụng lại code
    Noti noti = new Noti(this);
    // Lưu thông tin danh sách User
    ArrayList<User> listUser;
    // 2 biến lưu mã sinh viên của admin và password admin sau khi thoát hiển thị lại
    private String maSVAdmin;
    private String passwordAdmin;

    /**
     * Creates new form QLSinhVien
     */
    public QLSinhVien(){
       initComponents();
        panelDanhSach.setBorder(new TitledBorder("Danh sách thành viên"));
        panelButton.setBorder(new TitledBorder("Chức năng"));
        pack(); 
    }
    
    public QLSinhVien(String maSV, String password) {
        initComponents();
        panelDanhSach.setBorder(new TitledBorder("Danh sách thành viên"));
        panelButton.setBorder(new TitledBorder("Chức năng"));
        pack();
        this.maSVAdmin = maSV;
        this.passwordAdmin = password;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelDanhSach = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        // Tao DefaultTableModel va them row tieu de, va row thong tin person
        DefaultTableModel model = new DefaultTableModel(){
            @Override
            public boolean isCellEditable(int row, int column) {
                // chỉ được xem, không được sửa row and column nào hết
                return false;
            }
        };
        model.addColumn("ID");
        model.addColumn("Mã sinh viên");
        model.addColumn("Họ tên");
        model.addColumn("Khoa");
        model.addColumn("Lớp");
        model.addColumn("Password");
        model.addColumn("Email");
        model.addColumn("Trạng thái");
        model.addColumn("Thông tin");
        try{
            listUser = userController.getListUsers();
        }catch(IOException e){
            noti.showNotiError("Có lỗi: " + e.toString());
        }

        for(User user : listUser){
            Object[] row = {user.getId(), user.getMaSV(), user.getFullName(), user.getKhoa(), user.getLop(), user.getPassword(), user.getEmail(),userController.getStatus(user.getStatus()), userController.getCheck(user.getCheck()) };
            model.addRow(row);
        }
        tableDSSinhVien = new javax.swing.JTable(model);
        panelButton = new javax.swing.JPanel();
        btnRepair = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        btnRemove = new javax.swing.JButton();
        btnOut = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Quản lý thành viên");

        panelDanhSach.setBorder(javax.swing.BorderFactory.createTitledBorder("Danh sách thành viên"));

        // Lắng nghe sự kiện khi người dùng thay đổi giá trị trong JTable
        tableDSSinhVien.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(tableDSSinhVien);

        javax.swing.GroupLayout panelDanhSachLayout = new javax.swing.GroupLayout(panelDanhSach);
        panelDanhSach.setLayout(panelDanhSachLayout);
        panelDanhSachLayout.setHorizontalGroup(
            panelDanhSachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDanhSachLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1045, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelDanhSachLayout.setVerticalGroup(
            panelDanhSachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDanhSachLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(112, 112, 112))
        );

        panelButton.setBorder(javax.swing.BorderFactory.createTitledBorder("Chức năng"));

        btnRepair.setBackground(new java.awt.Color(0, 255, 153));
        btnRepair.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        btnRepair.setForeground(new java.awt.Color(204, 0, 0));
        btnRepair.setText("Sửa thông tin thành viên");
        btnRepair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRepairActionPerformed(evt);
            }
        });

        btnAdd.setBackground(new java.awt.Color(255, 255, 51));
        btnAdd.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        btnAdd.setText("Thêm thành viên");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnRemove.setBackground(new java.awt.Color(51, 0, 102));
        btnRemove.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        btnRemove.setForeground(new java.awt.Color(255, 255, 255));
        btnRemove.setText("Xóa thành viên");
        btnRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveActionPerformed(evt);
            }
        });

        btnOut.setBackground(new java.awt.Color(51, 0, 102));
        btnOut.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        btnOut.setForeground(new java.awt.Color(255, 255, 255));
        btnOut.setText("Thoát");
        btnOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelButtonLayout = new javax.swing.GroupLayout(panelButton);
        panelButton.setLayout(panelButtonLayout);
        panelButtonLayout.setHorizontalGroup(
            panelButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelButtonLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addComponent(btnRepair, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66)
                .addComponent(btnRemove, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 81, Short.MAX_VALUE)
                .addComponent(btnOut, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56))
        );
        panelButtonLayout.setVerticalGroup(
            panelButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelButtonLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRepair, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRemove, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnOut, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelDanhSach, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(panelButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(506, 506, 506))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelDanhSach, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(panelButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRepairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRepairActionPerformed
        // TODO add your handling code here:
        int index = tableDSSinhVien.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel) tableDSSinhVien.getModel();
        if (index != -1) {
            String maSV = (String) model.getValueAt(index, 1);
//            String hoTen = (String)model.getValueAt(index, 2);
//            String khoa = (String)model.getValueAt(index, 3);
//            String lop = (String)model.getValueAt(index, 4);
//            String password = (String)model.getValueAt(index, 5);
//            String email = (String)model.getValueAt(index, 6);
//            String status = (String)model.getValueAt(index, 7);
//            String check = (String)model.getValueAt(index, 8);
            new RepairInforUser(maSV).setVisible(true);
            this.setVisible(false);
        } else {
            noti.showNotiError("Vui lòng chọn thành viên muốn thay đổi thông tin");
        }
    }//GEN-LAST:event_btnRepairActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        new AddStudent().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveActionPerformed
        // TODO add your handling code here:
        int index = tableDSSinhVien.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel) tableDSSinhVien.getModel();
        if (index != -1) {
            try {
                String maSV = (String) model.getValueAt(index, 1);
                boolean kt = userController.removeUser(maSV);
                if (kt) {
                    noti.showNotiInformation("Xóa thành viên " + maSV + " thành công");
                    model = (DefaultTableModel)tableDSSinhVien.getModel();
                    try {
                        listUser = userController.getListUsers();
                    } catch (IOException e) {
                        noti.showNotiError("Có lỗi: " + e.toString());
                    }
                    // Xóa hết dữ liệu của DefaultTableModel ghi lại (Xóa các row)
                    model.setRowCount(0);
                    
                    // Ghi lại dữ liệu có ID đã được cập nhật
                    for (User user : listUser) {
                        Object[] row = {user.getId(), user.getMaSV(), user.getFullName(), user.getKhoa(), user.getLop(), user.getPassword(), user.getEmail(), userController.getStatus(user.getStatus()), userController.getCheck(user.getCheck())};
                        model.addRow(row);
                    }
                    model.fireTableDataChanged();
                }
            } catch (IOException e) {
                noti.showNotiError("Có lỗi: " + e.toString());
            }
        } else {
            noti.showNotiError("Vui lòng chọn thành viên muốn thay đổi thông tin");
        }
    }//GEN-LAST:event_btnRemoveActionPerformed

    private void btnOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOutActionPerformed
        // TODO add your handling code here:
        new HomeAdmin(maSVAdmin, passwordAdmin).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnOutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QLSinhVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QLSinhVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QLSinhVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QLSinhVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QLSinhVien().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnOut;
    private javax.swing.JButton btnRemove;
    private javax.swing.JButton btnRepair;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panelButton;
    private javax.swing.JPanel panelDanhSach;
    private javax.swing.JTable tableDSSinhVien;
    // End of variables declaration//GEN-END:variables
}
